### ISSUE TITLE
(t)weet doesn't work in Docker container

### ISSUE THREAD

**Issue by amorriscode** [coloradocolby/thokr#1]
## Description

After running a typing test and pressing `t`, nothing happens.

## To Reproduce

1. Run in Docker (`docker run -it coloradocolby/thokr`)
2. Complete a typing test
3. Press `t`

## Expected behavior

I would expect some sort of Twitter-friendly text to copy paste _or_ Twitter opens up with the tweet pre-filled.

## Environment

- OS: macOS
- Terminal Emulator: xterm
- Crate version: 0.1.0

**Comment by coloradocolby** [comment]
@amorriscode I saw this as well when testing in Docker. The reason is docker isn't aware of what your BROWSERS environment variable is. If you passed that in it _might_ work, but I wouldn't be surprised if it didn't given you're not actually taking the test on your host. 🤔 I'm not a huge fan of the copy/paste idea, especially in comparison to the convenience of how it nicely it works outside of docker. Maybe what I'll do is just hide the tweet option if I can rule out that a browser is unavailable.

**Comment by amorriscode** [comment]
That's fair. Worlde does the clipboard so I'd say that's a pretty safe/expected approach if available. I'd bet most people don't run it in Docker anyways but who knows!

**Comment by coloradocolby** [comment]
tracking https://github.com/amodm/webbrowser-rs/issues/46
