### ISSUE TITLE
Caret customization

### ISSUE THREAD

**Issue by KaniDev** [coloradocolby/thokr#14]
Hi ! Thanks for creating thokr, i'm having fun playing it in random terminals :)

My only issue is that I struggle noticing where my caret is sometimes (when i'm trying to see whether the key i hit registered or not); the underline is not always visible enough to me.

It would be cool to see an option to use different caret types (block, beam), perhaps even following current terminal settings ! (That could perhaps expand into cool fluff like pace carets like the other issue describes as well).

**Comment by jrnxf** [comment]
Hi @KaniDev! Sorry for not getting to this earlier! I think this would be a nice add, but at the minute I think the complexity of adding this is too great. It's been a while since I originally launched this project but I remember cursor support being a tricky add – that's why ultimately I chose to have a pseudo-cursor effect by underlining the currently active char. Should enough people be interested in adding this chime in, I'd be more open to prioritizing this, but for now I think I'll keep it as is.
